#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill ~/.config/background.jpg

bspc monitor -d '1 '  '2 '  '3 '  '4 '

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#151515"
bspc config focused_border_color "#ff9966"

bspc rule -a dmenu state=floating

killall -q polybar
polybar dock & polybar panel
